# -*- coding: utf-8 -*-
"""BMI calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sXRaSXbspjLzm5cnReJNqbj_NeiLk45L
"""

def calculate_bmi(weight, height):
    # Convert height from meters to centimeters
    height_cm = height * 100

    # Calculate BMI
    bmi = weight / (height_cm ** 2)

    return bmi

def classify_bmi(bmi):
    if bmi < 18.5:
        return "Underweight"
    elif 18.5 <= bmi < 24.9:
        return "Normal weight"
    elif 25.0 <= bmi < 29.9:
        return "Overweight"
    else:
        return "Obese"

weight = float(input("Enter your weight in kilograms: "))
height = float(input("Enter your height in meters: "))

bmi = calculate_bmi(weight, height)
bmi_category = classify_bmi(bmi)

print(f"Your BMI is: {bmi:.2f}")
print(f"You are classified as: {bmi_category}")